require("symbols-outline").setup {
  symbols = {
    File = { hl = "@Function" },
    Module = { hl = "@Namespace" },
    Namespace = { hl = "@Namespace" },
    Package = { hl = "@Namespace" },
    Class = { hl = "@Structure" },
    Method = { hl = "@Function" },
    Property = { hl = "@Field" },
    Field = { hl = "@Field" },
    Constructor = { hl = "@Constructor" },
    Enum = { hl = "@TypeDefinition" },
    Interface = { hl = "@Interface" },
    Function = { hl = "@Function" },
    Variable = { hl = "@Variable" },
    Constant = { hl = "@Constant" },
    String = { hl = "@String" },
    Number = { hl = "@Number" },
    Boolean = { hl = "@Boolean" },
    Array = { hl = "@Array" },
    Object = { hl = "@Dictionary" },
    Key = { hl = "@Keyword" },
    Null = { hl = "@Constant" },
    EnumMember = { hl = "@Field" },
  },
}
